# Generated by Django 4.1.1 on 2022-09-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
